"""AutoStream AI Models Package"""

from models.schemas import (
    WorkflowStep,
    WorkflowState,
    TrendItem,
    TrendSearchRequest,
    TrendResult,
    ScriptGenerationRequest,
    ScriptData,
    TTSRequest,
    VoiceOption,
    AudioData,
    AssetUploadRequest,
    AvatarData,
    LogoData,
    BackgroundData,
    VideoRenderRequest,
    VideoRenderData,
    VideoProgress,
    SuccessResponse,
    ErrorResponse,
    OllamaSettings,
    HeyGemSettings,
    FirecrawlSettings
)

__all__ = [
    "WorkflowStep",
    "WorkflowState",
    "TrendItem",
    "TrendSearchRequest",
    "TrendResult",
    "ScriptGenerationRequest",
    "ScriptData",
    "TTSRequest",
    "VoiceOption",
    "AudioData",
    "AssetUploadRequest",
    "AvatarData",
    "LogoData",
    "BackgroundData",
    "VideoRenderRequest",
    "VideoRenderData",
    "VideoProgress",
    "SuccessResponse",
    "ErrorResponse",
    "OllamaSettings",
    "HeyGemSettings",
    "FirecrawlSettings"
]
